-- AlterEnum
ALTER TYPE "ChallengeType" ADD VALUE 'ROUND_30_SPEEDRUN';
ALTER TYPE "ChallengeType" ADD VALUE 'ROUND_50_SPEEDRUN';
ALTER TYPE "ChallengeType" ADD VALUE 'ROUND_70_SPEEDRUN';
ALTER TYPE "ChallengeType" ADD VALUE 'ROUND_100_SPEEDRUN';
ALTER TYPE "ChallengeType" ADD VALUE 'EASTER_EGG_SPEEDRUN';
ALTER TYPE "ChallengeType" ADD VALUE 'GHOST_AND_SKULLS';
ALTER TYPE "ChallengeType" ADD VALUE 'ALIENS_BOSS_FIGHT';

-- AlterTable
ALTER TABLE "ChallengeLog" ADD COLUMN "useFortuneCards" BOOLEAN;
ALTER TABLE "ChallengeLog" ADD COLUMN "useDirectorsCut" BOOLEAN DEFAULT false;
