-- Advanced Warfare Exo Zombies: NO_EXO_SUIT, NO_EXO_HEALTH (all 4 maps), DOUBLE_FEATURE (Descent only).
ALTER TYPE "ChallengeType" ADD VALUE IF NOT EXISTS 'NO_EXO_SUIT';
ALTER TYPE "ChallengeType" ADD VALUE IF NOT EXISTS 'NO_EXO_HEALTH';
ALTER TYPE "ChallengeType" ADD VALUE IF NOT EXISTS 'DOUBLE_FEATURE';
